<a href="https://colab.research.google.com/github/Yash-Narnaware/ANN-CS-504/blob/main/PA_1_2024AIM1011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Programming Assignment - 1**
# **Building a Perceptron from Scratch**

*   Make your own copy of the file to work with

*   Template for Perceptron class (along with parameters and attributes) is given below. You need to fill the implementations for each of the functions defined in the class.

*   Three test cases are provided at the end for training and testing your perceptron for different cases.

*   Save your assignment in the format PA-1-2021CSBXXXX (with your entry number)and upload to Google Classroom


In [ ]:
# Import the necessary libraries
import numpy as np
import random

# TO DO: Add any other libraries (if needed)

In [ ]:
# Build Simple Perceptron Model (Rosenblatt) for Binary Classification
# [15 Points]
class Perceptron:

    """ Parameters:

        N  : Number of inputs to the perceptron
        LR : Learning rate between 0.0 and 1.0.

        Attributes:

        w : Weights corresponding to the inputs of the perceptron
            1D-arrary of length N+1 with w[0] used for bias
    """

    # TO DO: Initialize the weights and learning rate [1 Point]
    def __init__(self, N, LR = 0.01):

      self.N = N
      self.LR = LR
      self.w = np.array([0]*(self.N+1))
      # self.w = np.random.rand(self.N+1)
      self.threshold = 0

    # TO DO: Implement weighted sum of features and weights ( + bias) [2 Point]
    def weighted_sum(self, X):
      return np.dot(self.w,X)
      # Return

    # TO DO: Define the simple Step activation function [1 Point]
    def step_function(self, z):

      if z > self.threshold:
        return 1
      else:
        return 0
      # Return

    # TO DO: Define the Prediction (for X with current weights) [2 Points]
    def predict(self, X):

      #for predicting only, bias will not be added in input so adding the bias.
      if len(X) != self.N+1:
        X = np.insert(X,0,1)

      z = self.weighted_sum(X)

      return self.step_function(z)

      # Return

    # TO DO: Define the Loss function [1 Point]
    def loss(self, y_pred, y_true):

      # if y_pred != y_true:
      #   return 1 if y_true == 1 else -1
      # else:
      #   return 0

      return y_true - y_pred

      # Return

    # TO DO: Define training function - update weights [4 Points]
    def train(self, X, y_true):

      X = np.insert(X,0,1)

      y_pred = self.predict(X)
      loss = self.loss(y_pred,y_true)

      self.w = self.w + self.LR*loss*X

      print(self.w)


    # TO DO: Fit Training Set Using Perceptron Learning Algorithm [4 Points]
    """ Parameters:
        Input       : An array with shape [nSamples, nFeatures]
                      nSamples - number of samples
                      nFeatuers - number of featrures

        Output      : 1D-array of length [nSamples]
                      Binary classification of each sample

        nIterations : Number of iteration of learning aglorithm to run
                      over the training set
    """
    def fit(self, Input, Output, nIterations):

      for i in range(nIterations):

        #selecting random point
        # selected_point_index = random.randint(0,len(Input)-1)

        #selecting points in order.(In Rosenbaltt's model points are selected randomly but it may take more number of iterations for convergence of a model so I included both approaches)
        selected_point_index = i%len(Input)

        self.train(np.array(Input[selected_point_index]),Output[selected_point_index])


      # Use above defined functions in each iteration

In [ ]:
# TO DO: CODE FOR TRAINING AND TESTING PERCPETRON - AND GATE
# [3 Points]

And_inp = [[0,0],[0,1],[1,0],[1,1]]
And_out = [0,0,0,1]

And_GATE_Train = Perceptron(2,0.02)
And_GATE_Train.fit(And_inp,And_out,22)


[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0.02 0.02 0.02]
[0.   0.02 0.02]
[-0.02  0.02  0.  ]
[-0.02  0.02  0.  ]
[0.   0.04 0.02]
[0.   0.04 0.02]
[-0.02  0.04  0.  ]
[-0.04  0.02  0.  ]
[-0.02  0.04  0.02]
[-0.02  0.04  0.02]
[-0.02  0.04  0.02]
[-0.04  0.02  0.02]
[-0.02  0.04  0.04]
[-0.02  0.04  0.04]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]
[-0.04  0.04  0.02]


In [ ]:
#printing the final trained weights [bias,w1,w2]
print(And_GATE_Train.w)

[-0.04  0.04  0.02]


In [ ]:
#Testing AND gate
print("Input: [0,0], Output:",And_GATE_Train.predict([0,0]))
print("Input: [1,0], Output:",And_GATE_Train.predict([1,0]))
print("Input: [0,1], Output:",And_GATE_Train.predict([0,1]))
print("Input: [1,1], Output:",And_GATE_Train.predict([1,1]))

Input: [0,0], Output: 0
Input: [1,0], Output: 0
Input: [0,1], Output: 0
Input: [1,1], Output: 1


In [ ]:
# TO DO: CODE FOR TRAINING AND TESTING PERCPETRON - OR GATE
# [3 Points]

Or_inp = [[0,0],[0,1],[1,0],[1,1]]
Or_out = [0,1,1,1]

Or_GATE_Train = Perceptron(2)
Or_GATE_Train.fit(Or_inp,Or_out,12)

[0. 0. 0.]
[0.01 0.   0.01]
[0.01 0.   0.01]
[0.01 0.   0.01]
[0.   0.   0.01]
[0.   0.   0.01]
[0.01 0.01 0.01]
[0.01 0.01 0.01]
[0.   0.01 0.01]
[0.   0.01 0.01]
[0.   0.01 0.01]
[0.   0.01 0.01]


In [ ]:
#printing the final trained weights [bias(w0),w1,w2]
print(Or_GATE_Train.w)

[0.   0.01 0.01]


In [ ]:
#Testing OR gate
print("Input: [0,0], Output:",Or_GATE_Train.predict([0,0]))
print("Input: [1,0], Output:",Or_GATE_Train.predict([1,0]))
print("Input: [0,1], Output:",Or_GATE_Train.predict([0,1]))
print("Input: [1,1], Output:",Or_GATE_Train.predict([1,1]))

Input: [0,0], Output: 0
Input: [1,0], Output: 1
Input: [0,1], Output: 1
Input: [1,1], Output: 1


In [ ]:
# TO DO: Design a perceptron to decide if the binary pattern of Digits 0 - 9 is
# EVEN OR ODD - # [4 Points]
""" Binary pattern for Digits 0 - 9 given below
    0 -	[1	1	1	1	0	1	1	0	1	1	0	1	1	1	1]
1	- [1	1	0	0	1	0	0	1	1	0	1	0	1	1	1]
2	- [1	1	1	1	0	1	0	1	1	1	1	0	1	1	1]
3	- [1	1	1	1	1	1	0	1	1	0	0	1	1	1	1]
4	- [0	1	0	1	1	0	1	1	0	1	1	1	0	1	0]
5	- [1	1	1	1	1	0	0	1	1	0	0	1	1	1	1]
6	- [0	1	1	1	1	0	1	1	1	1	0	1	1	1	1]
7	- [1	1	1	1	0	1	0	1	0	0	1	0	0	1	0]
8	- [1	1	1	1	0	1	1	1	1	1	0	1	1	1	1]
9	- [1	1	1	1	0	1	1	1	1	0	1	1	1	1	0]

Use the above table as training data along with lables (0 - Odd, 1 - even) to
train a perceptron

Train for 10 iterations

Ater training, test on the following patterns and check if the perceptron output
is correct
Test1 = [1 1 1 1 0 1 1 0 1 1 0 1 1 0 1]
Test2 = [1 1 0 0 1 0 0 1 1 0 1 0 1 1 1]
"""
Bin_pattern_Inp = [[1,1,1,1,0,1,1,0,1,1,0,1,1,1,1],
              [1,1,0,0,1,0,0,1,1,0,1,0,1,1,1],
              [1,1,1,1,0,1,0,1,1,1,1,0,1,1,1],
              [1,1,1,1,1,1,0,1,1,0,0,1,1,1,1],
              [0,1,0,1,1,0,1,1,0,1,1,1,0,1,0],
              [1,1,1,1,1,0,0,1,1,0,0,1,1,1,1],
              [0,1,1,1,1,0,1,1,1,1,0,1,1,1,1],
              [1,1,1,1,0,1,0,1,0,0,1,0,0,1,0],
              [1,1,1,1,0,1,1,1,1,1,0,1,1,1,1],
              [1,1,1,1,0,1,1,1,1,0,1,1,1,1,0]]

Bin_pattern_Out = [1,0,1,0,1,0,1,0,1,0]

train_binary = Perceptron(15)
train_binary.fit(Bin_pattern_Inp,Bin_pattern_Out,10)


[0.01 0.01 0.01 0.01 0.01 0.   0.01 0.01 0.   0.01 0.01 0.   0.01 0.01
 0.01 0.01]
[ 0.    0.    0.    0.01  0.01 -0.01  0.01  0.01 -0.01  0.    0.01 -0.01
  0.01  0.    0.    0.  ]
[ 0.    0.    0.    0.01  0.01 -0.01  0.01  0.01 -0.01  0.    0.01 -0.01
  0.01  0.    0.    0.  ]
[-0.01 -0.01 -0.01  0.    0.   -0.02  0.    0.01 -0.02 -0.01  0.01 -0.01
  0.   -0.01 -0.01 -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]
[ 0.   -0.01  0.    0.    0.01 -0.01  0.    0.02 -0.01 -0.01  0.02  0.
  0.01 -0.01  0.   -0.01]


Question specifies to use 10 iterations thats why I used only 10 iterations but I am not getting consistant results with 10 iterations. I think training should be done for more number of iterations. To get consistant results I am choosing points in order instead of randomly selecting them.

In [ ]:
#Testing trained weights on testing data
print("Input:[1,1,1,1,0,1,1,0,1,1,0,1,1,0,1], Output:",train_binary.predict([1,1,1,1,0,1,1,0,1,1,0,1,1,0,1]))
print("Input:[1,1,0,0,1,0,0,1,1,0,1,0,1,1,1], Output:",train_binary.predict([1,1,0,0,1,0,0,1,1,0,1,0,1,1,1]))

Input:[1,1,1,1,0,1,1,0,1,1,0,1,1,0,1], Output: 1
Input:[1,1,0,0,1,0,0,1,1,0,1,0,1,1,1], Output: 0
