<a href="https://colab.research.google.com/github/Yash-Narnaware/ANN-CS-504/blob/main/PA_2_2024AIM1011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Programming Assignment - 2**
# **Building a simple MLP from Scratch**

*   Make your own copy of the file to work with

*   Template for MLP class (along with parameters and attributes) is given below. You need to fill the implementations for each of the functions defined in the class, including: ForwardPass, Backpropagation, Sigmoid Activation, Binary Cross Entropy Loss, etc.

* CONFIGURATION: Input Layer -> Hidden Layer -> Output Layer

*   Input Layer - 2 Nodes (x_1 & x_2)
*   Hidden Layer - 3 Nodes (h_1, h_2 & h_3)
*   Output Layer - 1 Node (y_pred)

*   Save your assignment in the format PA-1-2021CSBXXXX (with your entry number)and upload to Google Classroom


In [ ]:
# Import the necessary libraries
import numpy as np

# TO DO: Add any other libraries (if needed)

In [ ]:
# Build a simple MLP class with 2 inputs, 3 hidden nodes and one output
# Using FowardPass and Backpropagation iteratively to make predicitons
# [30 Points]
class MLP():

    """ Parameters:

      numInputs   : Number of inputs to the MLP
      numHidden   : Number of nodes in the hidden layer
      numOutputs  : Number of outputs from the MLP
      LR          : Learning rate between 0.0 and 1.0.

      Attributes:

      w1          : Weights corresponding to the inputs to the MLP
                    1D-arrary of length (numInputs + 1) with w1[0] used for bias

      w2          : Weights corresponding to the hidden nodes of the MLP
                    1D-arrary of length (numHidden + 1) with w2[0] used for bias

      z1          : Weighted-Sum input to the hidden layer
                    1D-arrary of length (numHidden)

      z2          : Weighted-Sum input to the output layer
                    1D-arrary of length (numOutputs)

      h1          : Output of the activation function at hidden layer
                    1D-arrary of length (numHidden)

    """

    # TO DO: Initialize all the parameters and internal attributes [3 Points]
    def __init__(self, numInputs = 2, numHidden = 3, numOutputs = 1, LR = 0.001):

        self.numInputs = numInputs
        self.numHidden = numHidden
        self.numOutputs = numOutputs
        self.LR = LR

        #first layer will have 3x3 weight matrix including bias
        self.W1 = np.zeros((self.numHidden,self.numInputs+1))

        # self.W1 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]])

        #second layer will have 1x4 weight matrix including bias
        #self.W2 = np.zeros((self.numOutputs,self.numHidden+1))

        self.W2 = np.array([0,0,0,0])
        # self.W2 = np.array([0.1,0.2,0.3,0.4])


        # self.W1 = np.random.randn(self.numHidden, self.numInputs + 1) * 0.01
        # self.W2 = np.random.randn(self.numOutputs, self.numHidden + 1) * 0.01


        # print("w2 in cnstructor",self.W2.shape);

        self.layer1_output = np.array([0,0,0])

        self.y_pred = 0


    # TO DO: Define the Sigmoid Activation function [2 Point]
    def Sigmoid(self, z):

        # Convert z to a numpy array if it's not already
        z = np.array(z)

        # Use np.clip to handle large values and prevent overflow
        z = np.clip(z, -500, 500)

        return 1/(1 + np.exp(-z))

        # Return

    # TO DO: Define the derivative of Sigmoid Activation function [2 Points]
    def delSigmoid(self, z):

        return self.Sigmoid(z)*(1 - self.Sigmoid(z))

        # Return

    # TO DO: Define the Binary Cross Entropy Cost function [3 Points]
    def BCECost(self, y_pred, y_true):

        y_pred = np.clip(y_pred, 0.0001, 0.9999)

        # return -(y_true*np.log(y_pred) + (1 - y_true)*np.log(1 - y_pred))
        return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

        # Return

    def delBCECost(self,y_pred, y_true):

        y_pred = np.clip(y_pred, 0.0001, 0.9999)

        return ((-y_true/y_pred) + ((1 - y_true)/(1 - y_pred)))



    # TO DO: Implement weighted sum of features and weights ( + bias) [2 Point]
    def weightedSum(self, X):

        X = np.array(X)

        if X.shape[0] == 3:
            # X = X.reshape(3,1)
            # print("X in ws", X)
            print("weighted_sum W1:",self.W1 @ X)
            return self.W1 @ X
        elif X.shape[0] == 4:
            print("weighted_sum W2:",self.W2 @ X)
            return (self.W2 @ X)

    # Return


    # TO DO: Implement function that performs ForwardPass of data through the network [5 Points]
    def forwardPass(self,X):#define function to feedforward the network

        # Use above defined functions to calculate intermediate values of the network

        # print("forward shape X",X.shape)

        self.layer1_output = self.Sigmoid(self.weightedSum(X))

        print("layer1_out:",self.layer1_output)

        # print("layer1_out shape",self.layer1_output.shape)

        layer_1_out_plus_bias = np.append(self.layer1_output,1)

        nn_output = self.Sigmoid(self.weightedSum(layer_1_out_plus_bias))

        return nn_output

        # Return (all necessary variables)

    # TO DO: Implement function for Backpropagation of error - calucation of derivates [5 Points]
    def backProp(self, y_true,layer,X):

        # #layer 2
        # delw2_11 = self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.layer1_output[0]
        # delw2_21 = self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.layer1_output[1]
        # delw2_31 = self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.layer1_output[2]
        # delb2_1 = self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)

        # # print(delw2_11,delw2_21,delw2_31,delb2_1)

        # #layer 1



        # delw1_11 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[0]*self.delSigmoid(self.layer1_output[0])*X[0]
        # delw1_21 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[0]*self.delSigmoid(self.layer1_output[0])*X[1]
        # delb1_1 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[0]*self.delSigmoid(self.layer1_output[0])

        # # print("fefwfwf ",self.W2,self.layer1_output,X)
        # delw1_12 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[1]*self.delSigmoid(self.layer1_output[1])*X[0]
        # delw1_22 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[1]*self.delSigmoid(self.layer1_output[1])*X[1]
        # delb1_2 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[1]*self.delSigmoid(self.layer1_output[1])

        # delw1_13 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[2]*self.delSigmoid(self.layer1_output[2])*X[0]
        # delw1_23 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[2]*self.delSigmoid(self.layer1_output[2])*X[1]
        # delb1_3 =  self.delBCECost(self.y_pred,y_true)*self.delSigmoid(self.y_pred)*self.W2[2]*self.delSigmoid(self.layer1_output[2])

        # # print("delw1_11",delw1_11)

        delta2 = self.delBCECost(self.y_pred, y_true) * self.delSigmoid(self.y_pred)
        dW2 = delta2 * np.append(self.layer1_output, 1)

        delta1 = delta2 * self.W2[:-1] * self.delSigmoid(self.layer1_output)
        dW1 = np.outer(delta1, X)



        if layer == 2:
            #temp2 = np.array()
            # return np.array([delw2_11,delw2_21,delw2_31,delb2_1])
            return dW2

        elif layer == 1:

            # return np.array([[delw1_11,delw1_21,delb1_1],[delw1_12,delw1_22,delb1_2],[delw1_13,delw1_23,delb1_3]])
            return dW1


      # Use above defined functions to calculate derivates in the network

      # Return (all necessary variables)


    # TO DO: Define the Prediction (for X with current weights) [2 Points]
    def predict(self, X):

        if len(X) != self.numInputs+1:
            X = np.append(X,1)

        z = self.forwardPass(X)
        print("z :",z)

        if z >= 0.5:
            return 1
        else:
            return 0



        # Return


    # TO DO: Define training function - update weights [3 Points]
    def train(self, X, y_true):

        #X = np.insert(X,0,1)
        X = np.append(X,1)

        # print("train ",self.W2)

        self.y_pred = self.predict(X)
        del_matrix_layer2 = self.backProp(y_true,2,X)
        del_matrix_layer1 = self.backProp(y_true,1,X)




        #loss = self.BCECost(y_pred,y_true)
        # print("print W2 before update: ",self.W2)
        # print("del matrix layer 2 ",del_matrix_layer2)
        W2 = self.W2 - self.LR*del_matrix_layer2
        self.W1 = self.W1 - self.LR*del_matrix_layer1

        self.W2 = W2


        # print(self.W1)
        # print(self.W2)

        # Use above defined functions in each iteration


    # TO DO: Fit Training Set Using Perceptron Learning Algorithm [3 Points]
    """ Parameters:
    Input       : An array with shape [nSamples, nFeatures]
                  nSamples - number of samples
                  nFeatuers - number of featrures

    Output      : 1D-array of length [nSamples]
                  Binary classification of each sample

    nIterations : Number of iteration of learning aglorithm to run
                  over the training set
    """
    def fit(self, Input, Output, nIterations):

        # Use above defined functions in each iteration
        # Store cost after each iteration for plotting at the end
        for i in range(nIterations):

            #print("fit W2 ",self.W2)

            #selecting random point
            # selected_point_index = random.randint(0,len(Input)-1)

            #selecting points in order.(In Rosenbaltt's model points are selected randomly but it may take more number of iterations for convergence of a model so I included both approaches)
            selected_point_index = i%len(Input)

            self.train(np.array(Input[selected_point_index]),Output[selected_point_index])


In [ ]:
XOR_GATE_Train = MLP()

In [ ]:
# TO DO: CODE FOR TRAINING AND TESTING MLP - XOR LOGIC GATE
# [3 Points]

XOR_inp = [[0,0],[0,1],[1,0],[1,1]]
XOR_out = [0,1,1,0]


XOR_GATE_Train = MLP()
XOR_GATE_Train.fit(XOR_inp,XOR_out,5000)

# Plot the cost as a function of iterations

Streaming output truncated to the last 5000 lines.
weighted_sum W1: [-1741.77042617 -1741.77042617 -1741.77042617]
layer1_out: [7.12457641e-218 7.12457641e-218 7.12457641e-218]
weighted_sum W2: -0.03270275602300623
z : 0.4918250395543459
weighted_sum W1: [-1725.0900491 -1725.0900491 -1725.0900491]
layer1_out: [7.12457641e-218 7.12457641e-218 7.12457641e-218]
weighted_sum W2: 2.4672972439769936
z : 0.9218171985030562
weighted_sum W1: [-8.24532685 -8.24532685 -8.24532685]
layer1_out: [0.00026241 0.00026241 0.00026241]
weighted_sum W2: 0.5084757441021258
z : 0.6244490853844097
weighted_sum W1: [-12.26573862 -12.26573862 -12.26573862]
layer1_out: [4.71037359e-06 4.71037359e-06 4.71037359e-06]
weighted_sum W2: -1.4648104305924894
z : 0.1877326847511792
weighted_sum W1: [-1738.05888479 -1738.05888479 -1738.05888479]
layer1_out: [7.12457641e-218 7.12457641e-218 7.12457641e-218]
weighted_sum W2: 1.0350585791469236
z : 0.737895430894182
weighted_sum W1: [-1731.72831329 -1731.72831329 -1731.7283

In [ ]:
print(XOR_GATE_Train.predict([0,0]))
print(XOR_GATE_Train.predict([0,1]))
print(XOR_GATE_Train.predict([1,0]))
print(XOR_GATE_Train.predict([1,1]))

weighted_sum W1: [-10.04536373 -10.04536373 -10.04536373]
layer1_out: [4.33845524e-05 4.33845524e-05 4.33845524e-05]
weighted_sum W2: -0.042240378153827994
z : 0.48944147533509674
0
weighted_sum W1: [-6.97468439 -6.97468439 -6.97468439]
layer1_out: [0.00093439 0.00093439 0.00093439]
weighted_sum W2: -0.01424190138184251
z : 0.496439584834774
0
weighted_sum W1: [-2842.45994199 -2842.45994199 -2842.45994199]
layer1_out: [7.12457641e-218 7.12457641e-218 7.12457641e-218]
weighted_sum W2: -0.043603674697346495
z : 0.4891008081393093
0
weighted_sum W1: [-2839.38926264 -2839.38926264 -2839.38926264]
layer1_out: [7.12457641e-218 7.12457641e-218 7.12457641e-218]
weighted_sum W2: -0.043603674697346495
z : 0.4891008081393093
0


In [ ]:
print(XOR_GATE_Train.W1)

[[-37.18615296   2.94029982  -6.44805645]
 [ -7.23061418  -2.33342688  -5.16769868]
 [-18.80684993  -0.58374932  -6.22415338]]


In [ ]:
# TO DO: CODE FOR TRAINING AND TESTING MLP - XNOR LOGIC GATE
# [2 Points]

XNOR_inp = [[0,0],[0,1],[1,0],[1,1]]
XNOR_out = [1,0,0,1]


XNOR_GATE_Train = MLP()
XNOR_GATE_Train.fit(XOR_inp,XOR_out,1000)

# Plot the cost as a function of iterations

z : 0.5
z : 0.031047153123923827
z : 0.6946123167222453
z : 0.6739210776427703
z : 0.16326027146789424
z : 0.17478869159178786
z : 0.7865051426783365
z : 0.7666766103228917
z : 0.2902914097017494
z : 0.28975892795564956
z : 0.860058665327707
z : 0.8450347551722658
z : 0.43193843380003416
z : 0.41836677709231757
z : 0.9119290522643871
z : 0.9016887427435739
z : 0.5783105388761075
z : 0.13627387383473324
z : 0.6651364632734111
z : 0.6679204134643643
z : 0.20977267997488966
z : 0.21718150988149937
z : 0.7769120176099372
z : 0.775591471693677
z : 0.3225878216951183
z : 0.3246111740211351
z : 0.8583623527888562
z : 0.8555798715173002
z : 0.45703691095428134
z : 0.45280279022726866
z : 0.9129535424698814
z : 0.9102221083843882
z : 0.5962267363359001
z : 0.1609278261647347
z : 0.6999175597502568
z : 0.7042895971428428
z : 0.2391667239401757
z : 0.2482769223057535
z : 0.8009110619943194
z : 0.8028131398287549
z : 0.35477985244221183
z : 0.36175466328089223
z : 0.8738820780926759
z : 0.87432256